In [1]:
import tfim
import numpy as np
from scipy import sparse
from scipy.sparse import linalg as spla
from scipy import linalg
import matplotlib.pyplot as plt
from scipy import optimize
import progressbar

In [2]:
PBC = True
L = [7]
J = 1

In [3]:
# Build lattice and basis
###################################
lattice = tfim.Lattice(L, PBC)
N = lattice.N
basis = tfim.IsingBasis(lattice)
###################################

In [4]:
seed_range = range(10);

Jij_array = [];

for i in seed_range:
    Jij = tfim.Jij_instance(N,J,"bimodal",i) 
    Jij_array.append(Jij)

In [6]:
# Calculate energy array:

indices_array = []

for Jij in Jij_array:
    Energies = -tfim.JZZ_SK_ME(basis,Jij)
    GS_energy = np.min(Energies)
    GS_indices = np.nonzero(Energies == GS_energy)[0]
    indices_array.append(GS_indices)
    

100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|


In [7]:
# Define Hamming distance
def Hamming_distance(state_1, state_2):
    return len(np.nonzero(state_1 - state_2)[0])

# Calculate Hamming distance array

def Hamming_array(GS_indices):
    Hamming = np.zeros((len(GS_indices), len(GS_indices)-1))
    for i, n in enumerate(GS_indices):
        basis_n = basis.state(n)
        for j, m in enumerate(np.delete(GS_indices,i)):
            basis_m = basis.state(m)
            Hamming[i, j] = Hamming_distance(basis_n, basis_m)
    return Hamming

In [8]:
def search_2(array):
    if np.amin(array) == 4:
        return True
    else:
        return False

In [10]:
# search for Hamming distance 2

seed_list = []

for index, indices in enumerate(indices_array):
    if search_2(Hamming_array(indices)):
        seed_list.append(index)
    print(Hamming_array(indices))
        
print(seed_list)

[[7.]
 [7.]]
[[7.]
 [7.]]
[[1. 1. 4. 5. 4. 5. 3. 2. 5. 4. 2. 3. 2. 3. 6. 6. 7.]
 [1. 2. 5. 4. 3. 6. 2. 1. 6. 5. 1. 4. 3. 2. 5. 7. 6.]
 [1. 2. 5. 6. 5. 4. 4. 3. 4. 3. 3. 2. 1. 2. 7. 5. 6.]
 [4. 5. 5. 1. 2. 1. 3. 4. 3. 4. 6. 5. 6. 7. 2. 2. 3.]
 [5. 4. 6. 1. 1. 2. 2. 3. 4. 5. 5. 6. 7. 6. 1. 3. 2.]
 [4. 3. 5. 2. 1. 3. 1. 2. 5. 6. 4. 7. 6. 5. 2. 4. 3.]
 [5. 6. 4. 1. 2. 3. 4. 5. 2. 3. 7. 4. 5. 6. 3. 1. 2.]
 [3. 2. 4. 3. 2. 1. 4. 1. 6. 7. 3. 6. 5. 4. 3. 5. 4.]
 [2. 1. 3. 4. 3. 2. 5. 1. 7. 6. 2. 5. 4. 3. 4. 6. 5.]
 [5. 6. 4. 3. 4. 5. 2. 6. 7. 1. 5. 2. 3. 4. 3. 1. 2.]
 [4. 5. 3. 4. 5. 6. 3. 7. 6. 1. 4. 1. 2. 3. 4. 2. 3.]
 [2. 1. 3. 6. 5. 4. 7. 3. 2. 5. 4. 3. 2. 1. 4. 6. 5.]
 [3. 4. 2. 5. 6. 7. 4. 6. 5. 2. 1. 3. 1. 2. 5. 3. 4.]
 [2. 3. 1. 6. 7. 6. 5. 5. 4. 3. 2. 2. 1. 1. 6. 4. 5.]
 [3. 2. 2. 7. 6. 5. 6. 4. 3. 4. 3. 1. 2. 1. 5. 5. 4.]
 [6. 5. 7. 2. 1. 2. 3. 3. 4. 3. 4. 4. 5. 6. 5. 2. 1.]
 [6. 7. 5. 2. 3. 4. 1. 5. 6. 1. 2. 6. 3. 4. 5. 2. 1.]
 [7. 6. 6. 3. 2. 3. 2. 4. 5. 2. 3. 5. 4. 5. 4. 1. 1.]]
[

In [ ]:
# pass Jij, GS_states only, build each order of perturbation theory one at a time
# module: 1st order, and second order matrices